name: Create release

on:
  push:
    branches:
     - main
    paths:
      - Dockerfile
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  create-container:
    runs-on: ubuntu-latest
    outputs:
      tool-info: ${{ steps.create-container.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: make sure we have git
        run: |
          sudo apt-get install -y git

      - name: capture the commit hash
        run: |
          git log -1 --format="%H" >CommitHash
          git config --list >RepoInfo

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/nodejs-wasm-build:latest

      - name: Inspect
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/nodejs-wasm-build:latest
          docker image inspect ghcr.io/${{ github.repository_owner }}/nodejs-wasm-build:latest
