name: Create release

on:
  push:
    branches:
     - main
    paths:
      - Dockerfile
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create-container:
    runs-on: ubuntu-latest
    outputs:
      tool-info: ${{ steps.create-container.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: mhdawson/nodejs-wasm-build:latest

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: mhdawson/nodejs-wasm-build:latest
      - name: Inspect
        run: |
          docker image inspect mhdawson/nodejs:latest          
